### ISSUE TITLE
Mutated code is shown incorrectly

### ISSUE THREAD

**Issue by simondel** [infosupport/stryker#15]
escodegen applies formatting to the code. This usually doesn't matter, but in a few cases it does. This causes the mutated line of code to be shown incorrectly because line numbers have changed.

An example can be seen using the [escodegen online demo](https://estools.github.io/escodegen/demo/index.html) by using the following code:

```js
var arr = ['A', 'B'];
var obj = { name: 'Simon', age: 22 };
```

A *possible solution* is to ignore this feature of escodegen and search the AST for the code which should be on the specified line number. By generating this part of the AST and removing all line breaks, the correct line of code could be shown in the report.

**Comment by simondel** [comment]
I have tried to solve this issue by not generating code at all, instead by manually editing the original code string. However, this is quite buggy, because you don't always know the exact column which has been edited.

For example: The `*` in `a * b` has `column: 1` while it's at column 3.

This issue becomes even more apparent when the code is split along multiple lines. For example: if the 'test' of an if statement which covers multiple lines has to be changed to `false`.

Only generating the part of the AST (using escodegen) which has actually been changed seems like an easier solution now. Shall I try this @nicojs ?

**Comment by nicojs** [comment]
Sounds good to me. 

Indeed i can see that we cannot find the exact location of the *-character in your example. Only the entire expression. Having the location of the entire expression is exactly enough for fitting in the escodegen generated piece
