### ISSUE TITLE
Rename all files to <filename>.ts and add TypeScript build process

### ISSUE THREAD

**Issue by nicojs** [infosupport/stryker#18]
As we want to transform our code to [TypeScript] (http://typescriptlang.org), the first step will be to transform our code *.ts files. We should add those to source control instead of our js files. We should also add a compile step into our build system

**Comment by nicojs** [comment]
Done in branch `typescript-migration`. We'll close this issue once it is in `develop`.

**Comment by simondel** [comment]
This can be closed, right?

**Comment by nicojs** [comment]
Yes please
Op 24 feb. 2016 21:10 schreef "Simon de Lang" <notifications@github.com>:
