### ISSUE TITLE
Replace all constructor functions with TS classes

### ISSUE THREAD

**Issue by nicojs** [infosupport/stryker#19]
For the [TypeScript] (http://typescriptlang.org) migration we should replace all constructor functions by actual typescript classes. We'll start doing this in the `typescript-migration` branch and comment here when we convert each file.

**Comment by nicojs** [comment]
- [ ] mutations/BaseMutation.ts
- [ ] mutations/BaseOperatorMutation.ts
- [ ] mutations/ConditionalBoundayMutation.ts
- [ ] mutations/MathMutation.ts
- [ ] mutations/RemoveConditionalsMutation.ts
- [ ] mutations/ReverseConditionalMutation.ts
- [ ] mutations/UnaryOperatorMutation.ts
- [ ] reporters/BaseReporter.ts
- [ ] reporters/ConsoleReporter.ts
- [ ] utils/FileUtils.ts
- [ ] utils/ParserUtils.ts
- [ ] utils/TypeUtils.ts
- [ ] testrunners/BaseTestRunner.ts
- [ ] testrunners/JasmineTestRunner.ts
- [ ] testrunners/KarmaServerWorker.ts
- [ ] testrunners/KarmaTestRunner.ts
- [ ] AbstractSyntaxTreeNode.ts
- [ ] Mutant.ts
- [ ] MutationRegistry.ts
- [ ] Mutator.ts
- [ ] ReporterFactory.ts
- [ ] Stryker.ts
- [ ] TestFile.ts
- [ ] TestResult.ts
- [ ] TestRunnerFactory.ts

**Comment by simondel** [comment]
A manual integration test can be executed using the following command from the root directory of the project after TypeScript compilation:

```
node dist\src\Stryker.js -s test\sampleProject\src\Add.js,test\sampleProject\src\Circle.js -t test\sampleProject\test\AddSpec.js,test\sampleProject\test\CircleSpec.js
```

**Comment by simondel** [comment]
@nicojs Could you take a look at Stryker.ts in commit [a828da0](https://github.com/infosupport/stryker/commit/a828da0aa2b23d2a15c8447c75f823a429d390a1)?

**Comment by nicojs** [comment]
I just did. It looks good. I added my comments to the commit. 

What more do we need to fix to close this issue? I think after we don't have non-emit-preventing warnings, we're good to go. We should than configure the grunt-ts task to not allow for these type of warnings anymore.

**Comment by nicojs** [comment]
I think it is more important to have no non-emit-preventing warnings. A non-emit-preventing warning is basically a compiler error and should be fixed asap. I feel like noImplicitAny is a next step, for an other issue. We can then fix all implicit any's in one pull request. Do you agree?

**Comment by simondel** [comment]
We don't have any non-emit-preventing warnings anymore. We do have 188 warnings if we turn on `noImplicitAny`. I personally think fixing 188 warnings in one pull request is a bit much so I'd prefer using the method we used to solve this issue.

**Comment by nicojs** [comment]
Closed as there were no non-emit-preventing warnings anymore. I created issue #21 for the `noImplicitAny` check
