### ISSUE TITLE
Rewrite karma test runner to keep the karma server open

### ISSUE THREAD

**Issue by nicojs** [infosupport/stryker#25]
We should rewrite the karma test runner to keep the karma server open instead for the entire test run, instead of opening up a new node process for each mutation test run. This can be done using the way of working in the [karma-coverage-per-test](https://github.com/nicojs/karma-coverage-per-test/) prototype.

We can maybe also add a new abstraction for starting child processes and handling them, so we don't need to recreate it at a later stage (server side unit tests).

**Comment by simondel** [comment]
See also #27
