### ISSUE TITLE
Update readme for v0.1

### ISSUE THREAD

**Issue by nicojs** [infosupport/stryker#50]

**Comment by simondel** [comment]
The installation still points to `node node_modules/stryker/src/Stryker.js --help` while the src of stryker is now in the dist folder (until we change the package.json)

**Comment by nicojs** [comment]
Do you think we should move the documentation about the mutations themselves to docs/mutations.md or something? We can point to that from the readme.md (with full url: https://github.com/infosupport/stryker/blob/master/docs/mutations.md)

**Comment by simondel** [comment]
@nicojs I think it's best to leave the mutations in the main README. This way all documentation is one place. If the size of the README increases in the future, it could be smart to move the mutations.

I have started working on this issue on https://github.com/infosupport/stryker/tree/v0.1-preparation
