### ISSUE TITLE
Karma-runner coverage is reporting more than expected

### ISSUE THREAD

**Issue by nicojs** [infosupport/stryker#55]
It seems that Karma-coverage is reporting more than expected. For example: the result of `Add should be able to add two numbers` (see below).

I will bring forward the in-memory karma-coverage reporting to see if that solves this issue

EDIT Removed too long example:

**Comment by nicojs** [comment]
Found what the issue is. Take statement from circle.js for example:

```javascript
var getCircumference = function(radius) {
  //Function to test multiple math mutations in a single function.
  return 2 * Math.PI * radius;
};
```

This gets reported as 2 statements:

1. from 1:1 to 4:2
2. from 3:2 to 3:30

Statement 1 is covered by literately every tests (the function declaration itself of course). I propose the following solution to fix this issue:

Think from the point of the mutation. Let's say the mutation is in statement to (for example: we mutate it to be `return 2 / Math.PI * radius;`). We first look for the *smallest* statement

**Comment by simondel** [comment]
See also #58
