### ISSUE TITLE
NPM install: compile TS files

### ISSUE THREAD

**Issue by simondel** [infosupport/stryker#59]
The Typescript files should be compiled to JavaScript files during a NPM install

**Comment by nicojs** [comment]
Better would be:

* Add `grunt test` in `pre-publish`
* Alter package.json to **not** include src files, only the files in the *dist* folder (*.d.ts and *.js)
* Configure a travis build to do the actual publishing: https://docs.travis-ci.com/user/deployment/npm/

**Comment by nicojs** [comment]
Maybe we should include the src files, comparable to https://www.npmjs.com/package/reflect-metadata
