### ISSUE TITLE
(bug) No notification when initial test run fails for some reason

### ISSUE THREAD

**Issue by nicojs** [infosupport/stryker#64]
When Karma errors in the initial test run it is treated as if there are no tests. When you turn off the `silent` flag you can see the following output:

```
INFO: Running initial test run
using config {"browsers":["PhantomJS"],"frameworks":["jasmine"],"autoWatch":false,"singleRun":false,"plugins":["karma-jasmine","karma-phantomjs-launcher","karma-coverage"],"files":[...],"port":1234,"coverageReporter":{"type":"in-memory"},"preprocessors":{...},"reporters":["coverage"]}
24 03 2016 22:14:08.982:INFO [karma]: Karma v0.13.22 server started at http://localhost:1234/
24 03 2016 22:14:08.986:INFO [launcher]: Starting browser PhantomJS
24 03 2016 22:14:09.494:INFO [PhantomJS 1.9.8 (Windows 8 0.0.0)]: Connected on socket /#tOMWTOX3l_ZzzTYYAAAA with id 67783735
karma run done with  1
```
I've tested this using our internal KarmaDesigner project with the following arguments:

```javascript
	"program": "${workspaceRoot}/node_modules/stryker/dist/src/Stryker.js",
			"stopOnEntry": false,
			"args": ["-s","app/scripts/app.js,app/scripts/httpConfig.js,app/scripts/resources/ConditionRsc.js,app/scripts/resources/PageDtoRsc.js,app/scripts/resources/SurveyResultRsc.js,app/scripts/resources/SurveyRsc.js,app/scripts/resources/SurveySummariesPageRsc.js,app/scripts/routes.js,app/scripts/services/dragDropHelper.js,app/scripts/services/idGenerator.js,app/scripts/services/jsonHelper.js,app/scripts/services/localStorage.js,app/scripts/services/modalHelper.js,app/scripts/services/notificationStorage.js,app/scripts/services/random.js,app/scripts/services/surveyFind.js,app/scripts/services/surveyForEach.js,app/scripts/services/surveyStorage.js,app/scripts/services/tenantHelper.js","-o","test/spec/controllers/editFactRuleSet.test.js"],
```

For clarification: i deliberately not included the angular js sources in the `otherFiles` list. I would expect Stryker to show me this (`cannot call module on undefined` or something)

**Comment by simondel** [comment]
The funny thing is, if you keep it running it will actually log the error due to the `listenToBrowserError` function:
```
  ReferenceError: Can't find variable: angular
  at C:/Users/simonl/AppData/Local/Temp/stryker/2122910/test-runner-source-files2275308/app.js:18
```

But that message is only logged when mutants are being tested. Odd.

**Comment by nicojs** [comment]
Ah yes! Thank you @simondel. The latest version of stryker isn't calling the `listenToBrowserError` function and thus isn't listening to the errors. We should listen to the errors and handle them in a clear way.

**Comment by simondel** [comment]
Is it an idea to include an optional field `errorMessage` in the RunResult? This message could be logged when a test fails or something else happens during the initial test run. Also, Stryker shouldn't continue running if there was a browser error in the initial test run.

**Comment by nicojs** [comment]
Yeah, that's probably what i want to do. But it think stryker should not continue when the test result is TestResult.Error, regardless of the error message. So in the `KarmaTestRunner` we should decide if an error is due to no tests being ran or because an actual error. I will do a proposal in a PR.
