### ISSUE TITLE
Contributor guide

### ISSUE THREAD

**Issue by wmeints** [infosupport/stryker#68]
Can we get a contributor guide in the repo so people know how they can get their changes included?
I have a standard template ready to go: https://github.com/infosupport/contribute-md-template

If you like I can make a pull request for it as well :-)

**Comment by simondel** [comment]
I think this is a great idea! Now that we're on the topic of contributing, what do you think of putting stryker on http://up-for-grabs.net/ ?

**Comment by nicojs** [comment]
I started developing this feature. Should we also add ad pre-commit git hook? We could for require git commit messages to conform to [the angular spec] (https://docs.google.com/document/d/1rk04jEuGfk9kYzfqCuOlPTSJw3hEDZJTBN5E5f1SALo/edit) really easy by combining [validate-commit-message](https://github.com/Frikki/validate-commit-message) with [ghooks](https://github.com/gtramontina/ghooks)

I think free publicity using up-for-grabs is an excellent idea :+1:

**Comment by nicojs** [comment]
On the other hand... maybe it's not a good idea to add a barrier for people to contribute. Probably better to leave commit messages open for now.

**Comment by simondel** [comment]
Closed with #78
